#
# Copyright (c) 2023-2025 Ruben Perez Hidalgo (rubenperez038 at gmail dot com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

# This file is used during development and testing, not for production

services:
  redis:
    image: "redis:7.4.2-alpine"
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  mysql:
    image: "mysql:9.2.0"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=servertech_user
      - MYSQL_PASSWORD=temp_password
    ports:
      - "3306:3306"
    volumes:
      - "./server/tools/db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql"
